version: '2'

services:
    consul:
        image: smebberson/alpine-consul:dev
    consului:
        image: smebberson/alpine-consul-ui:dev
        ports:
            - 8500:8500
    static:
        build: ./static
        ports:
            - 80:80
    cache:
        image: smebberson/alpine-consul-redis:dev
    app:
        build: ./app
