version: '2'

services:
    consul:
        build: ./consul
    consului:
        build: ./consul-ui
        ports:
            - 8500:8500
    static:
        build: ./static
        ports:
            - 80:80
